import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.LinearIndependent.Defs
import Mathlib.LinearAlgebra.Matrix.Defs
import Mathlib.Tactic
import QEC.Stabilizer.BinarySymplectic.Core
import QEC.Stabilizer.PauliGroup.NQubitOperator
import QEC.Stabilizer.PauliGroup.NQubitElement

namespace Quantum

variable {n : ℕ}

/-!
# Check matrix for stabilizer generators

The check matrix of a list of n-qubit Pauli group elements has one row per element:
row i is the symplectic vector (Fin (n + n) → ZMod 2) of the i-th element's operator part.
Rows are linearly independent over ZMod 2 iff the generators are independent.
-/

namespace NQubitPauliGroupElement

/-- The check matrix of a list of n-qubit Pauli group elements.

  Each row is the symplectic vector (over ZMod 2) of the corresponding element's
  operator part. Column indices are Fin (n + n): first n columns are X-components,
  last n are Z-components. -/
def checkMatrix (L : List (NQubitPauliGroupElement n)) :
    Matrix (Fin L.length) (Fin (n + n)) (ZMod 2) :=
  fun i j => NQubitPauliOperator.toSymplectic (L.get i).operators j

/-- The rows of the check matrix are linearly independent over ZMod 2.

  This is the predicate used (together with `rowsLinearIndependent_iff_forall`
  from `CheckMatrixDecidable`) to deduce that the generators form an independent set: no generator lies
  in the subgroup generated by the others. -/
def rowsLinearIndependent (L : List (NQubitPauliGroupElement n)) : Prop :=
  LinearIndependent (ZMod 2) (fun i : Fin L.length => checkMatrix L i)

end NQubitPauliGroupElement

end Quantum
