import Mathlib.Tactic
import QEC.Stabilizer.Core.StabilizerGroup
import QEC.Stabilizer.Core.SubgroupLemmas
import QEC.Stabilizer.Core.CSSNoNegI
import QEC.Stabilizer.Core.Centralizer
import QEC.Stabilizer.PauliGroup.Commutation
import QEC.Stabilizer.PauliGroup.CommutationTactics
import QEC.Stabilizer.BinarySymplectic.Core
import QEC.Stabilizer.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.BinarySymplectic.CheckMatrixDecidable
import QEC.Stabilizer.BinarySymplectic.SymplecticSpan
import QEC.Stabilizer.Core.StabilizerCode
import QEC.Stabilizer.BinarySymplectic.IndependentEquiv
import QEC.Stabilizer.BinarySymplectic.SymplecticInner
import QEC.Stabilizer.PauliGroup.NQubitOperator

namespace Quantum
open scoped BigOperators

namespace StabilizerGroup
namespace Steane7

/-!
# The Steane [[7,1,3]] code (CSS stabilizer generators)

We use the standard CSS presentation coming from the classical [7,4,3] Hamming code.

Let the parity-check rows (supports) be:
- r₁ = {0,1,2,4}
- r₂ = {0,1,3,5}
- r₃ = {0,2,3,6}

Then the Steane stabilizer is generated by:
- Z-checks: Z on each row support (3 generators)
- X-checks: X on each row support (3 generators)

Cross-commutation holds because every Z-row intersects every X-row in an even number of qubits.
We package the resulting subgroup as a `StabilizerGroup 7`.
-/

open NQubitPauliGroupElement

/-!
## Generators
-/

/-- Z-check on row r₁ = {0,1,2,4}: Z on qubits 0,1,2,4 and I elsewhere. -/
def Z1 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.Z).set 1 PauliOperator.Z).set 2
      PauliOperator.Z |>.set 4 PauliOperator.Z⟩

/-- Z-check on row r₂ = {0,1,3,5}: Z on qubits 0,1,3,5 and I elsewhere. -/
def Z2 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.Z).set 1 PauliOperator.Z).set 3
      PauliOperator.Z |>.set 5 PauliOperator.Z⟩

/-- Z-check on row r₃ = {0,2,3,6}: Z on qubits 0,2,3,6 and I elsewhere. -/
def Z3 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.Z).set 2 PauliOperator.Z).set 3
      PauliOperator.Z |>.set 6 PauliOperator.Z⟩

/-- X-check on row r₁ = {0,1,2,4}: X on qubits 0,1,2,4 and I elsewhere. -/
def X1 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.X).set 1 PauliOperator.X).set 2
      PauliOperator.X |>.set 4 PauliOperator.X⟩

/-- X-check on row r₂ = {0,1,3,5}: X on qubits 0,1,3,5 and I elsewhere. -/
def X2 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.X).set 1 PauliOperator.X).set 3
      PauliOperator.X |>.set 5 PauliOperator.X⟩

/-- X-check on row r₃ = {0,2,3,6}: X on qubits 0,2,3,6 and I elsewhere. -/
def X3 : NQubitPauliGroupElement 7 :=
  ⟨0,
    (((NQubitPauliOperator.identity 7).set 0 PauliOperator.X).set 2 PauliOperator.X).set 3
      PauliOperator.X |>.set 6 PauliOperator.X⟩

/-- The three Z-check generators (Z on each parity-check row). -/
def ZGenerators : Set (NQubitPauliGroupElement 7) :=
  {Z1, Z2, Z3}

/-- The three X-check generators (X on each parity-check row). -/
def XGenerators : Set (NQubitPauliGroupElement 7) :=
  {X1, X2, X3}

/-- The full generator set: Z-checks and X-checks. -/
def generators : Set (NQubitPauliGroupElement 7) :=
  ZGenerators ∪ XGenerators

/-- The Steane stabilizer subgroup: closure of the six generators. -/
def subgroup : Subgroup (NQubitPauliGroupElement 7) :=
  Subgroup.closure generators

/-!
## Typing facts: Z-type / X-type generators
-/

/-- Each Z-generator is Z-type (I or Z on each qubit). -/
lemma ZGenerators_are_ZType :
    ∀ g, g ∈ ZGenerators → NQubitPauliGroupElement.IsZTypeElement g := by
  classical
  intro g hg
  rcases (by simpa [ZGenerators] using hg) with rfl | rfl | rfl <;>
    · constructor
      · rfl
      · intro i
        fin_cases i <;>
          simp [PauliOperator.IsZType, Z1, Z2, Z3, NQubitPauliOperator.set,
            NQubitPauliOperator.identity]

/-- Each X-generator is X-type (I or X on each qubit). -/
lemma XGenerators_are_XType :
    ∀ g, g ∈ XGenerators → NQubitPauliGroupElement.IsXTypeElement g := by
  classical
  intro g hg
  rcases (by simpa [XGenerators] using hg) with rfl | rfl | rfl <;>
    · constructor
      · rfl
      · intro i
        fin_cases i <;>
          simp [PauliOperator.IsXType, X1, X2, X3, NQubitPauliOperator.set,
            NQubitPauliOperator.identity]

/-!
## Cross-commutation: Z generators commute with X generators

We use `commutes_iff_even_anticommutes` and compute the anticommute set explicitly.
-/

private lemma Z1_comm_X1 : Z1 * X1 = X1 * Z1 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z1.operators X1.operators
  have hfilter : (Finset.univ.filter p) = ({0, 1, 2, 4} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z1, X1, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z1_comm_X2 : Z1 * X2 = X2 * Z1 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z1.operators X2.operators
  have hfilter : (Finset.univ.filter p) = ({0, 1} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z1, X2, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z1_comm_X3 : Z1 * X3 = X3 * Z1 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z1.operators X3.operators
  have hfilter : (Finset.univ.filter p) = ({0, 2} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z1, X3, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z2_comm_X1 : Z2 * X1 = X1 * Z2 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z2.operators X1.operators
  have hfilter : (Finset.univ.filter p) = ({0, 1} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z2, X1, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z2_comm_X2 : Z2 * X2 = X2 * Z2 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z2.operators X2.operators
  have hfilter : (Finset.univ.filter p) = ({0, 1, 3, 5} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z2, X2, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z2_comm_X3 : Z2 * X3 = X3 * Z2 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z2.operators X3.operators
  have hfilter : (Finset.univ.filter p) = ({0, 3} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z2, X3, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z3_comm_X1 : Z3 * X1 = X1 * Z3 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z3.operators X1.operators
  have hfilter : (Finset.univ.filter p) = ({0, 2} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z3, X1, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z3_comm_X2 : Z3 * X2 = X2 * Z3 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z3.operators X2.operators
  have hfilter : (Finset.univ.filter p) = ({0, 3} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z3, X2, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma Z3_comm_X3 : Z3 * X3 = X3 * Z3 := by
  classical
  pauli_comm_even_anticommutes
  let p := NQubitPauliGroupElement.anticommutesAt (n := 7) Z3.operators X3.operators
  have hfilter : (Finset.univ.filter p) = ({0, 2, 3, 6} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [p, NQubitPauliGroupElement.anticommutesAt, Z3, X3, NQubitPauliOperator.set,
        NQubitPauliOperator.identity, PauliOperator.mulOp]
  rw [hfilter]; decide

/-- Every Z-generator commutes with every X-generator (even intersection of row supports). -/
lemma ZGenerators_commute_XGenerators :
    ∀ z ∈ ZGenerators, ∀ x ∈ XGenerators, z * x = x * z := by
  classical
  intro z hz x hx
  rcases (by simpa [ZGenerators] using hz) with rfl | rfl | rfl <;>
    rcases (by simpa [XGenerators] using hx) with rfl | rfl | rfl
  · exact Z1_comm_X1
  · exact Z1_comm_X2
  · exact Z1_comm_X3
  · exact Z2_comm_X1
  · exact Z2_comm_X2
  · exact Z2_comm_X3
  · exact Z3_comm_X1
  · exact Z3_comm_X2
  · exact Z3_comm_X3

/-!
## Pairwise commutation of all generators
-/

private lemma ZType_commutes {g h : NQubitPauliGroupElement 7}
    (hg : NQubitPauliGroupElement.IsZTypeElement g)
    (hh : NQubitPauliGroupElement.IsZTypeElement h) :
    g * h = h * g := by
  classical
  apply NQubitPauliGroupElement.commutes_of_componentwise_commutes
  intro i
  have hg' := hg.2 i
  have hh' := hh.2 i
  rcases hg' with hgI | hgZ <;> rcases hh' with hhI | hhZ
  · simp [PauliOperator.mulOp, hgI, hhI]
  · simp [PauliOperator.mulOp, hgI, hhZ]
  · simp [PauliOperator.mulOp, hgZ, hhI]
  · simp [PauliOperator.mulOp, hgZ, hhZ]

private lemma XType_commutes {g h : NQubitPauliGroupElement 7}
    (hg : NQubitPauliGroupElement.IsXTypeElement g)
    (hh : NQubitPauliGroupElement.IsXTypeElement h) :
    g * h = h * g := by
  classical
  apply NQubitPauliGroupElement.commutes_of_componentwise_commutes
  intro i
  have hg' := hg.2 i
  have hh' := hh.2 i
  rcases hg' with hgI | hgX <;> rcases hh' with hhI | hhX
  · simp [PauliOperator.mulOp, hgI, hhI]
  · simp [PauliOperator.mulOp, hgI, hhX]
  · simp [PauliOperator.mulOp, hgX, hhI]
  · simp [PauliOperator.mulOp, hgX, hhX]

/-- All six generators pairwise commute. -/
theorem generators_commute :
    ∀ g ∈ generators, ∀ h ∈ generators, g * h = h * g := by
  classical
  intro g hg h hh
  have hg' : g ∈ ZGenerators ∨ g ∈ XGenerators := by simpa [generators] using hg
  have hh' : h ∈ ZGenerators ∨ h ∈ XGenerators := by simpa [generators] using hh
  rcases hg' with hgZ | hgX <;> rcases hh' with hhZ | hhX
  · exact ZType_commutes (ZGenerators_are_ZType g hgZ) (ZGenerators_are_ZType h hhZ)
  · exact ZGenerators_commute_XGenerators g hgZ h hhX
  · simpa using (ZGenerators_commute_XGenerators h hhZ g hgX).symm
  · exact XType_commutes (XGenerators_are_XType g hgX) (XGenerators_are_XType h hhX)

/-!
## No `-I` in the Steane stabilizer subgroup (CSS lemma)
-/

/-- The Steane subgroup does not contain −I (CSS lemma with Z- and X-generators). -/
theorem negIdentity_not_mem :
    negIdentity 7 ∉ subgroup := by
  have hZX : ∀ z ∈ ZGenerators, ∀ x ∈ XGenerators, z * x = x * z :=
    ZGenerators_commute_XGenerators
  simpa [subgroup, generators] using
    (CSS.negIdentity_not_mem_closure_union (n := 7) ZGenerators XGenerators
      ZGenerators_are_ZType XGenerators_are_XType hZX)

/-- Generators as a list (for symplectic-span arguments and bundled stabilizer group). -/
def generatorsList : List (NQubitPauliGroupElement 7) :=
  [Z1, Z2, Z3, X1, X2, X3]

/-- The list of generators has the same elements as the generator set. -/
lemma listToSet_generatorsList : NQubitPauliGroupElement.listToSet generatorsList = generators := by
  simp only [generatorsList, generators, ZGenerators, XGenerators,
    NQubitPauliGroupElement.listToSet_cons, NQubitPauliGroupElement.listToSet_nil]
  ext g
  simp only [Set.mem_insert_iff, Set.mem_union, Set.mem_singleton_iff, Set.mem_empty_iff_false,
    or_false, or_assoc]

/-!
## Bundled `StabilizerGroup 7`
-/

/-- Steane code as `StabilizerGroup 7` (canonical: from generator list). -/
noncomputable def stabilizerGroup : StabilizerGroup 7 :=
  mkStabilizerFromGenerators 7 generatorsList
    (by rw [listToSet_generatorsList]; exact generators_commute)
    (by rw [listToSet_generatorsList]; exact negIdentity_not_mem)

lemma stabilizerGroup_toSubgroup_eq : stabilizerGroup.toSubgroup = subgroup := by
  simp only [stabilizerGroup, mkStabilizerFromGenerators, subgroup]
  rw [listToSet_generatorsList]

/-!
## Logical operators

Logical X = X on all 7 qubits, logical Z = Z on all 7 qubits. They commute with the
stabilizer, anticommute with each other, and are not in the subgroup (proved via
symplectic span).
-/

/-- Every element of the generators list has phase power 0. -/
lemma AllPhaseZero_generatorsList : NQubitPauliGroupElement.AllPhaseZero generatorsList := by
  rw [generatorsList, NQubitPauliGroupElement.AllPhaseZero_cons]
  exact ⟨rfl, (NQubitPauliGroupElement.AllPhaseZero_cons _ _).mpr
    ⟨rfl, (NQubitPauliGroupElement.AllPhaseZero_cons _ _).mpr
      ⟨rfl, (NQubitPauliGroupElement.AllPhaseZero_cons _ _).mpr
        ⟨rfl, (NQubitPauliGroupElement.AllPhaseZero_cons _ _).mpr
          ⟨rfl, (NQubitPauliGroupElement.AllPhaseZero_cons _ _).mpr
            ⟨rfl, NQubitPauliGroupElement.AllPhaseZero_nil⟩⟩⟩⟩⟩⟩

/-- The check-matrix rows of the Steane generators are linearly independent. -/
theorem rowsLinearIndependent_generatorsList :
    NQubitPauliGroupElement.rowsLinearIndependent generatorsList := by decide

/-- The Steane generator list is an independent generating set. -/
theorem GeneratorsIndependent_7_generatorsList : GeneratorsIndependent 7 generatorsList :=
  GeneratorsIndependent_of_rowsLinearIndependent 7 generatorsList
    rowsLinearIndependent_generatorsList

/-- Logical X: X on all seven qubits. -/
def logicalX : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.X 7⟩

/-- Logical Z: Z on all seven qubits. -/
def logicalZ : NQubitPauliGroupElement 7 :=
  ⟨0, NQubitPauliOperator.Z 7⟩

/-- Logical X and logical Z anticommute (symplectic inner product 1 mod 2). -/
theorem logicalX_anticommutes_logicalZ : NQubitPauliGroupElement.Anticommute logicalX logicalZ :=
  NQubitPauliOperator.allX_allZ_anticommute 7 (by decide)

private lemma logicalX_commutes_Z1 : logicalX * Z1 = Z1 * logicalX := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalX.operators Z1.operators)) =
        ({0, 1, 2, 4} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX, Z1,
        NQubitPauliOperator.X, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalX_commutes_Z2 : logicalX * Z2 = Z2 * logicalX := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalX.operators Z2.operators)) =
        ({0, 1, 3, 5} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX, Z2,
        NQubitPauliOperator.X, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalX_commutes_Z3 : logicalX * Z3 = Z3 * logicalX := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalX.operators Z3.operators)) =
        ({0, 2, 3, 6} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalX, Z3,
        NQubitPauliOperator.X, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalX_commutes_X1 : logicalX * X1 = X1 * logicalX := by
  pauli_comm_componentwise [logicalX, X1, NQubitPauliOperator.X]

private lemma logicalX_commutes_X2 : logicalX * X2 = X2 * logicalX := by
  pauli_comm_componentwise [logicalX, X2, NQubitPauliOperator.X]

private lemma logicalX_commutes_X3 : logicalX * X3 = X3 * logicalX := by
  pauli_comm_componentwise [logicalX, X3, NQubitPauliOperator.X]

/-- Logical X commutes with every element of the stabilizer. -/
theorem logicalX_mem_centralizer : logicalX ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff, stabilizerGroup_toSubgroup_eq, subgroup]
  rw [Subgroup.forall_comm_closure_iff]
  intro s hs
  simp [generators] at hs
  rcases hs with hgZ | hgX
  · rcases (by simpa [ZGenerators] using hgZ) with rfl | rfl | rfl
    · exact logicalX_commutes_Z1.symm
    · exact logicalX_commutes_Z2.symm
    · exact logicalX_commutes_Z3.symm
  · rcases (by simpa [XGenerators] using hgX) with rfl | rfl | rfl
    · exact logicalX_commutes_X1.symm
    · exact logicalX_commutes_X2.symm
    · exact logicalX_commutes_X3.symm

private lemma logicalZ_commutes_Z1 : logicalZ * Z1 = Z1 * logicalZ := by
  pauli_comm_componentwise [logicalZ, Z1, NQubitPauliOperator.Z]

private lemma logicalZ_commutes_Z2 : logicalZ * Z2 = Z2 * logicalZ := by
  pauli_comm_componentwise [logicalZ, Z2, NQubitPauliOperator.Z]

private lemma logicalZ_commutes_Z3 : logicalZ * Z3 = Z3 * logicalZ := by
  pauli_comm_componentwise [logicalZ, Z3, NQubitPauliOperator.Z]

private lemma logicalZ_commutes_X1 : logicalZ * X1 = X1 * logicalZ := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalZ.operators X1.operators)) =
        ({0, 1, 2, 4} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalZ, X1,
        NQubitPauliOperator.Z, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalZ_commutes_X2 : logicalZ * X2 = X2 * logicalZ := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalZ.operators X2.operators)) =
        ({0, 1, 3, 5} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalZ, X2,
        NQubitPauliOperator.Z, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

private lemma logicalZ_commutes_X3 : logicalZ * X3 = X3 * logicalZ := by
  classical
  pauli_comm_even_anticommutes
  have hfilter :
      (Finset.univ.filter
            (NQubitPauliGroupElement.anticommutesAt (n := 7) logicalZ.operators X3.operators)) =
        ({0, 2, 3, 6} : Finset (Fin 7)) := by
    ext i; fin_cases i <;>
      simp [Finset.mem_filter, NQubitPauliGroupElement.anticommutesAt, logicalZ, X3,
        NQubitPauliOperator.Z, NQubitPauliOperator.set, NQubitPauliOperator.identity,
        PauliOperator.mulOp]
  rw [hfilter]; decide

/-- Logical Z commutes with every element of the stabilizer. -/
theorem logicalZ_mem_centralizer : logicalZ ∈ centralizer stabilizerGroup := by
  rw [StabilizerGroup.mem_centralizer_iff, stabilizerGroup_toSubgroup_eq, subgroup]
  rw [Subgroup.forall_comm_closure_iff]
  intro s hs
  simp [generators] at hs
  rcases hs with hgZ | hgX
  · rcases (by simpa [ZGenerators] using hgZ) with rfl | rfl | rfl
    · exact logicalZ_commutes_Z1.symm
    · exact logicalZ_commutes_Z2.symm
    · exact logicalZ_commutes_Z3.symm
  · rcases (by simpa [XGenerators] using hgX) with rfl | rfl | rfl
    · exact logicalZ_commutes_X1.symm
    · exact logicalZ_commutes_X2.symm
    · exact logicalZ_commutes_X3.symm

/-!
## StabilizerCode [[7, 1]]
-/

private def logicalOpsSteane7 : Fin 1 → LogicalQubitOps 7 stabilizerGroup :=
  fun _ => ⟨logicalX, logicalZ, logicalX_mem_centralizer, logicalZ_mem_centralizer,
    logicalX_anticommutes_logicalZ⟩

/-- The Steane code as a stabilizer code [[7, 1]]: one logical qubit. -/
noncomputable def stabilizerCode : StabilizerCode 7 1 where
  hk := by decide
  generatorsList := generatorsList
  generators_length := rfl
  generators_phaseZero := AllPhaseZero_generatorsList
  generators_independent := GeneratorsIndependent_7_generatorsList
  generators_commute := by rw [listToSet_generatorsList]; exact generators_commute
  closure_no_neg_identity := by rw [listToSet_generatorsList]; exact negIdentity_not_mem
  logicalOps := logicalOpsSteane7
  logical_commute_cross := fun ℓ ℓ' h => (h (Subsingleton.elim ℓ ℓ')).elim

end Steane7
end StabilizerGroup

end Quantum
