/-
Copyright (c) 2024 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
import Particles.StandardModel.Basic
import Mathlib.GroupTheory.QuotientGroup.Defs
/-!

# The Pati-Salam Model

The Pati-Salam model is a petite unified theory that unifies the Standard Model gauge group into
`SU(4) x SU(2) x SU(2)`.

-/

namespace PatiSalam
/-!

## The Pati-Salam gauge group.

-/

/-- The gauge group of the Pati-Salam model (unquotiented by ℤ₂), i.e., `SU(4) × SU(2) × SU(2)`. -/
abbrev GaugeGroupI : Type :=
  Matrix.specialUnitaryGroup (Fin 4) ℂ ×
    Matrix.specialUnitaryGroup (Fin 2) ℂ ×
    Matrix.specialUnitaryGroup (Fin 2) ℂ

namespace GaugeGroupI

/-- The underlying `SU(4)` component of a Pati-Salam gauge transformation. -/
def toSU4 : GaugeGroupI →* Matrix.specialUnitaryGroup (Fin 4) ℂ where
  toFun g := g.1
  map_one' := rfl
  map_mul' _ _ := rfl

/-- The left `SU(2)` component of a Pati-Salam gauge transformation. -/
def toSU2L : GaugeGroupI →* Matrix.specialUnitaryGroup (Fin 2) ℂ where
  toFun g := g.2.1
  map_one' := rfl
  map_mul' _ _ := rfl

/-- The right `SU(2)` component of a Pati-Salam gauge transformation. -/
def toSU2R : GaugeGroupI →* Matrix.specialUnitaryGroup (Fin 2) ℂ where
  toFun g := g.2.2
  map_one' := rfl
  map_mul' _ _ := rfl

@[ext]
lemma ext {g g' : GaugeGroupI} (h4 : toSU4 g = toSU4 g') (hL : toSU2L g = toSU2L g')
    (hR : toSU2R g = toSU2R g') : g = g' := by
  rcases g with ⟨g4, gL, gR⟩
  rcases g' with ⟨g4', gL', gR'⟩
  simp [toSU4, toSU2L, toSU2R] at h4 hL hR
  simp_all

end GaugeGroupI

/-- The central element `-1` in `SU(4)`. -/
noncomputable def minusOneSU4 : Matrix.specialUnitaryGroup (Fin 4) ℂ := by
  refine ⟨(-1 : Matrix (Fin 4) (Fin 4) ℂ), ?_, ?_⟩
  · change (-1 : Matrix (Fin 4) (Fin 4) ℂ) ∈ Matrix.unitaryGroup (Fin 4) ℂ
    rw [Matrix.mem_unitaryGroup_iff]
    simp
  · norm_num [Matrix.det_neg]

/-- The central element `-1` in `SU(2)`. -/
noncomputable def minusOneSU2 : Matrix.specialUnitaryGroup (Fin 2) ℂ := by
  refine ⟨(-1 : Matrix (Fin 2) (Fin 2) ℂ), ?_, ?_⟩
  · change (-1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ Matrix.unitaryGroup (Fin 2) ℂ
    rw [Matrix.mem_unitaryGroup_iff]
    simp
  · norm_num [Matrix.det_neg]

/-- The nontrivial central element `(-1,-1,-1)` of the unquotiented Pati-Salam gauge group. -/
noncomputable def gaugeGroupℤ₂Elem : GaugeGroupI :=
  (minusOneSU4, minusOneSU2, minusOneSU2)

/-- The central order-two element `(-1,-1,-1)` in the unquotiented Pati-Salam gauge group. -/
lemma minusOneSU4_sq : minusOneSU4 ^ 2 = 1 := by
  ext i j
  simp [minusOneSU4]

lemma minusOneSU2_sq : minusOneSU2 ^ 2 = 1 := by
  ext i j
  simp [minusOneSU2]

/-- The scalar matrix `-1` commutes with every element of `SU(4)`. -/
lemma minusOneSU4_commute (g : Matrix.specialUnitaryGroup (Fin 4) ℂ) :
    g * minusOneSU4 = minusOneSU4 * g := by
  ext i j
  change ((↑g : Matrix (Fin 4) (Fin 4) ℂ) * (-(1 : Matrix (Fin 4) (Fin 4) ℂ))) i j =
    ((-(1 : Matrix (Fin 4) (Fin 4) ℂ)) * (↑g : Matrix (Fin 4) (Fin 4) ℂ)) i j
  rw [Matrix.mul_neg, Matrix.neg_mul, Matrix.mul_one, Matrix.one_mul]

/-- The scalar matrix `-1` commutes with every element of `SU(2)`. -/
lemma minusOneSU2_commute (g : Matrix.specialUnitaryGroup (Fin 2) ℂ) :
    g * minusOneSU2 = minusOneSU2 * g := by
  ext i j
  change ((↑g : Matrix (Fin 2) (Fin 2) ℂ) * (-(1 : Matrix (Fin 2) (Fin 2) ℂ))) i j =
    ((-(1 : Matrix (Fin 2) (Fin 2) ℂ)) * (↑g : Matrix (Fin 2) (Fin 2) ℂ)) i j
  rw [Matrix.mul_neg, Matrix.neg_mul, Matrix.mul_one, Matrix.one_mul]

lemma gaugeGroupℤ₂Elem_sq : gaugeGroupℤ₂Elem ^ 2 = 1 := by
  apply GaugeGroupI.ext
  · simpa [gaugeGroupℤ₂Elem, GaugeGroupI.toSU4] using minusOneSU4_sq
  · simpa [gaugeGroupℤ₂Elem, GaugeGroupI.toSU2L] using minusOneSU2_sq
  · simpa [gaugeGroupℤ₂Elem, GaugeGroupI.toSU2R] using minusOneSU2_sq

/-- The distinguished `(-1,-1,-1)` element is central in `GaugeGroupI`. -/
lemma gaugeGroupℤ₂Elem_commute (g : GaugeGroupI) :
    g * gaugeGroupℤ₂Elem = gaugeGroupℤ₂Elem * g := by
  apply GaugeGroupI.ext
  · simpa [GaugeGroupI.toSU4, gaugeGroupℤ₂Elem] using minusOneSU4_commute (GaugeGroupI.toSU4 g)
  · simpa [GaugeGroupI.toSU2L, gaugeGroupℤ₂Elem] using minusOneSU2_commute (GaugeGroupI.toSU2L g)
  · simpa [GaugeGroupI.toSU2R, gaugeGroupℤ₂Elem] using minusOneSU2_commute (GaugeGroupI.toSU2R g)

/-- The ℤ₂-subgroup of the unquotiented gauge group generated by the nontrivial element
`(-1, -1, -1)`.

See https://math.ucr.edu/home/baez/guts.pdf
-/
noncomputable def gaugeGroupℤ₂SubGroup : Subgroup GaugeGroupI := Subgroup.zpowers gaugeGroupℤ₂Elem

instance gaugeGroupℤ₂SubGroup_normal : gaugeGroupℤ₂SubGroup.Normal := by
  refine ⟨fun a ha g => ?_⟩
  rcases Subgroup.mem_zpowers_iff.mp ha with ⟨k, rfl⟩
  have hcomm : Commute g gaugeGroupℤ₂Elem := gaugeGroupℤ₂Elem_commute g
  have h_eq : g * gaugeGroupℤ₂Elem ^ k * g⁻¹ = gaugeGroupℤ₂Elem ^ k := by
    calc
      g * gaugeGroupℤ₂Elem ^ k * g⁻¹ = gaugeGroupℤ₂Elem ^ k * g * g⁻¹ := by
        rw [(hcomm.zpow_right k).eq]
      _ = gaugeGroupℤ₂Elem ^ k := by simp [mul_assoc]
  exact h_eq.symm ▸ Subgroup.zpow_mem_zpowers gaugeGroupℤ₂Elem k

/-- The Pati-Salam gauge group with its distinguished central `ℤ₂` quotient.

This is the quotient of `GaugeGroupI` by the subgroup generated by `(-1,-1,-1)`.

See https://math.ucr.edu/home/baez/guts.pdf
-/
abbrev GaugeGroupℤ₂ : Type := GaugeGroupI ⧸ gaugeGroupℤ₂SubGroup

/-- The canonical projection from the unquotiented gauge group to the `ℤ₂` quotient. -/
noncomputable def toGaugeGroupℤ₂ : GaugeGroupI →* GaugeGroupℤ₂ :=
  QuotientGroup.mk' gaugeGroupℤ₂SubGroup

@[simp]
lemma toGaugeGroupℤ₂_gaugeGroupℤ₂Elem : toGaugeGroupℤ₂ gaugeGroupℤ₂Elem = 1 := by
  exact (QuotientGroup.eq_one_iff gaugeGroupℤ₂Elem).mpr <| Subgroup.mem_zpowers gaugeGroupℤ₂Elem

end PatiSalam
