import QEC.Stabilizer.Core.StabilizerGroup
import QEC.Stabilizer.Core.Centralizer
import QEC.Stabilizer.Core.LogicalOperators
import QEC.Stabilizer.Core.SubgroupLemmas
import QEC.Stabilizer.PauliGroup.Commutation
import QEC.Stabilizer.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.BinarySymplectic.IndependentEquiv

namespace Quantum
namespace StabilizerGroup

variable {n k : ℕ}

/-!
# Stabilizer codes [[n, k]]

A **stabilizer code** encoding k logical qubits on n physical qubits consists of:

1. A stabilizer group S (abelian, no −I) with **exactly n − k independent generators**, so the
   code space has dimension 2^k.

2. For each logical qubit ℓ : Fin k, a pair of logical operators X̄ℓ and Z̄ℓ that:
   - Lie in the centralizer of S (commute with every stabilizer element).
   - Anticommute with each other (X̄ℓ Z̄ℓ = −Z̄ℓ X̄ℓ).
   - Commute with all logical operators for other logical qubits ℓ′ ≠ ℓ.
   - Are not in S (so they act nontrivially on the code space).

This structure captures the standard [[n, k, d]] notion (without distance d).
-/

/-!
## Independent generators (Prop)

Independence is stated as a Prop so that proofs can be carried out using the check-matrix
representation (e.g. `rowsLinearIndependent`) and then lifted here.
-/

/-- A list of n-qubit Pauli group elements is an independent generating set if no element
    lies in the subgroup generated by the others. Prove this by showing the check-matrix
    rows are linearly independent (over ZMod 2), then use
    `GeneratorsIndependent_of_rowsLinearIndependent`. -/
def GeneratorsIndependent (n : ℕ) (L : List (NQubitPauliGroupElement n)) : Prop :=
  Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet L)

/-- If the check-matrix rows of `L` are linearly independent, then `L` is an
    independent generating set. Use this to prove `GeneratorsIndependent n L` by
    proving `NQubitPauliGroupElement.rowsLinearIndependent L`. -/
theorem GeneratorsIndependent_of_rowsLinearIndependent (n : ℕ)
    (L : List (NQubitPauliGroupElement n))
    (h : NQubitPauliGroupElement.rowsLinearIndependent L) :
    GeneratorsIndependent n L :=
  NQubitPauliGroupElement.rowsLinearIndependent_implies_independentGenerators L h

/-!
## Stabilizer group from generators

The stabilizer is defined as the closure of the generator list (single source of truth).
-/

/-- Build a stabilizer group from a list of generators that pairwise commute and whose
    closure does not contain -I. -/
def mkStabilizerFromGenerators (n : ℕ) (L : List (NQubitPauliGroupElement n))
    (h_comm : ∀ g ∈ NQubitPauliGroupElement.listToSet L,
      ∀ h ∈ NQubitPauliGroupElement.listToSet L, g * h = h * g)
    (h_no_neg : negIdentity n ∉ Subgroup.closure (NQubitPauliGroupElement.listToSet L)) :
    StabilizerGroup n where
  toSubgroup := Subgroup.closure (NQubitPauliGroupElement.listToSet L)
  is_abelian := fun g h hg hh =>
    Subgroup.abelian_closure_of_pairwise_commute
      (NQubitPauliGroupElement.listToSet L) h_comm g hg h hh
  no_neg_identity := h_no_neg

/-- A stabilizer code encoding k logical qubits on n physical qubits.

    The stabilizer is given by a generating list of length n − k (single source of truth).
    Generators must pairwise commute and their closure must not contain -I. Every generator
    has phase power 0 for the symplectic/check-matrix representation. The logical operators
    are bundled per logical qubit and commute across different qubits.
-/
structure StabilizerCode (n k : ℕ) where
  /-- We need k ≤ n so that n - k generator count is meaningful. -/
  hk : k ≤ n
  /-- A list of generators whose closure is the stabilizer subgroup. -/
  generatorsList : List (NQubitPauliGroupElement n)
  /-- There are exactly n - k generators (so the code space has dimension 2^k). -/
  generators_length : generatorsList.length = n - k
  /-- Every generator has phase power 0 (for symplectic/check-matrix representation). -/
  generators_phaseZero : NQubitPauliGroupElement.AllPhaseZero generatorsList
  /-- The generator list is independent (prove via check-matrix: rowsLinearIndependent). -/
  generators_independent : GeneratorsIndependent n generatorsList
  /-- Generators pairwise commute. -/
  generators_commute : ∀ g ∈ NQubitPauliGroupElement.listToSet generatorsList,
    ∀ h ∈ NQubitPauliGroupElement.listToSet generatorsList, g * h = h * g
  /-- The closure of the generators does not contain -I. -/
  closure_no_neg_identity : negIdentity n ∉ Subgroup.closure
    (NQubitPauliGroupElement.listToSet generatorsList)
  /-- For each logical qubit, logical X and Z in the centralizer, anticommuting. -/
  logicalOps : Fin k → LogicalQubitOps n (mkStabilizerFromGenerators n generatorsList
    generators_commute closure_no_neg_identity)
  /-- Logical operators for different logical qubits commute. -/
  logical_commute_cross : ∀ ℓ ℓ', ℓ ≠ ℓ' →
    ((logicalOps ℓ).xOp * (logicalOps ℓ').xOp = (logicalOps ℓ').xOp * (logicalOps ℓ).xOp ∧
      (logicalOps ℓ).xOp * (logicalOps ℓ').zOp = (logicalOps ℓ').zOp * (logicalOps ℓ).xOp ∧
      (logicalOps ℓ).zOp * (logicalOps ℓ').xOp = (logicalOps ℓ').xOp * (logicalOps ℓ).zOp ∧
      (logicalOps ℓ).zOp * (logicalOps ℓ').zOp = (logicalOps ℓ').zOp * (logicalOps ℓ).zOp)

namespace StabilizerCode

/-- The stabilizer group of the code (derived from the generator list). -/
def toStabilizerGroup (C : StabilizerCode n k) : StabilizerGroup n :=
  mkStabilizerFromGenerators n C.generatorsList C.generators_commute C.closure_no_neg_identity

/-- Logical X for logical qubit ℓ. -/
def logicalX (C : StabilizerCode n k) (ℓ : Fin k) : NQubitPauliGroupElement n :=
  (C.logicalOps ℓ).xOp

/-- Logical Z for logical qubit ℓ. -/
def logicalZ (C : StabilizerCode n k) (ℓ : Fin k) : NQubitPauliGroupElement n :=
  (C.logicalOps ℓ).zOp

/-- Logical X for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalX_not_mem_subgroup (C : StabilizerCode n k) (ℓ : Fin k) :
    C.logicalX ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  (C.logicalOps ℓ).xOp_not_mem

/-- Logical Z for qubit ℓ is not in the stabilizer subgroup. -/
theorem logicalZ_not_mem_subgroup (C : StabilizerCode n k) (ℓ : Fin k) :
    C.logicalZ ℓ ∉ C.toStabilizerGroup.toSubgroup :=
  (C.logicalOps ℓ).zOp_not_mem

/-- Each logical X is a nontrivial logical operator. -/
theorem logicalX_nontrivial (C : StabilizerCode n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalX ℓ) C.toStabilizerGroup :=
  (C.logicalOps ℓ).xOp_nontrivial

/-- Each logical Z is a nontrivial logical operator. -/
theorem logicalZ_nontrivial (C : StabilizerCode n k) (ℓ : Fin k) :
    IsNontrivialLogicalOperator (C.logicalZ ℓ) C.toStabilizerGroup :=
  (C.logicalOps ℓ).zOp_nontrivial

/-- The generator set is an independent generating set for the stabilizer. -/
theorem generators_independentGenerators (C : StabilizerCode n k) :
    Subgroup.IndependentGenerators (NQubitPauliGroupElement.listToSet C.generatorsList) :=
  C.generators_independent

end StabilizerCode

end StabilizerGroup
end Quantum
