/-
Copyright (c) 2025 Lean-QuantumInfo contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.

Canonical Commutation Relations (CCR) and Canonical Anti-commutation Relations (CAR).

The CCR algebra (Weyl form) is the universal C*-algebra generated by unitaries
W(f), f ∈ H, satisfying the Weyl relations:
  W(f)W(g) = exp(-i/2 σ(f,g)) W(f+g)
where σ is the symplectic form (imaginary part of the inner product).

The CAR algebra is the universal C*-algebra generated by a(f), f ∈ H, satisfying:
  {a(f), a*(g)} = ⟨f, g⟩ · 1
  {a(f), a(g)} = 0
-/
import Mathlib

universe u

variable (H : Type u) [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace Quantum

open scoped ComplexInnerProductSpace

/-! ## CCR Algebra (Weyl Form) -/

/-- Abstract CCR algebra: a type A equipped with Weyl operators satisfying
the canonical commutation relations in Weyl form. -/
class CCRAlgebra (A : Type*) [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] where
  /-- The Weyl operator W(f) for each f ∈ H. -/
  W : H → A
  /-- Weyl operators are unitary: W(f)* W(f) = 1. -/
  W_star_mul : ∀ f, star (W f) * W f = 1
  /-- Weyl operators are unitary: W(f) W(f)* = 1. -/
  W_mul_star : ∀ f, W f * star (W f) = 1
  /-- W(0) = 1. -/
  W_zero : W 0 = 1
  /-- The Weyl relation: W(f)W(g) = exp(-i/2 Im⟨f,g⟩) · W(f+g). -/
  weyl_relation : ∀ f g,
    W f * W g = Complex.exp (-Complex.I / 2 * (@inner ℂ H _ f g - @inner ℂ H _ g f) / 2) • W (f + g)
  /-- Continuity: t ↦ W(tf) is strongly continuous. -/
  strong_continuity : ∀ f, Continuous (fun (t : ℝ) => W (t • f))

namespace CCRAlgebra

variable {H} {A : Type*} [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [CCRAlgebra H A]

/-- W(f)* = W(-f).
Proof: From unitarity W(f)*W(f) = 1 and the Weyl relation W(-f)W(f) = exp(0)·W(0) = 1,
we get that both star(W(f)) and W(-f) are left inverses of W(f).
Since W(f) also has a right inverse (star(W(f))), left inverses are unique. -/
theorem W_star (f : H) : star (W (H := H) (A := A) f) = W (-f) := by
  let w : H → A := CCRAlgebra.W (H := H) (A := A)
  change star (w f) = w (-f)
  have hw_zero : w 0 = (1 : A) := CCRAlgebra.W_zero (H := H) (A := A)
  have h_left : w (-f) * w f = (1 : A) := by
    have hw :
        w (-f) * w f =
          Complex.exp (-Complex.I / 2 * (@inner ℂ H _ (-f) f - @inner ℂ H _ f (-f)) / 2) •
            w ((-f) + f) :=
      CCRAlgebra.weyl_relation (H := H) (A := A) (-f) f
    rw [hw]
    simp [hw_zero]
  symm
  calc
    w (-f) = w (-f) * 1 := by simp
    _ = w (-f) * (w f * star (w f)) := by rw [CCRAlgebra.W_mul_star (H := H) (A := A) f]
    _ = (w (-f) * w f) * star (w f) := by simp [mul_assoc]
    _ = (1 : A) * star (w f) := by rw [h_left]
    _ = star (w f) := by simp

/-- The symplectic form σ(f,g) = Im⟨f,g⟩. -/
noncomputable def symplecticForm (f g : H) : ℝ :=
  (@inner ℂ H _ f g).im

/-- The symplectic form is antisymmetric: σ(f,g) = -σ(g,f). -/
theorem symplecticForm_antisymm (f g : H) :
    symplecticForm f g = -symplecticForm g f := by
  unfold symplecticForm
  simpa using (inner_im_symm (𝕜 := ℂ) f g)

/-- The symplectic form of a vector with itself vanishes: σ(f,f) = 0. -/
theorem symplecticForm_self (f : H) : symplecticForm f f = 0 := by
  unfold symplecticForm
  rw [inner_self_eq_norm_sq_to_K]
  norm_num [pow_two]

end CCRAlgebra

/-! ## CAR Algebra -/

/-- Abstract CAR algebra: a type A equipped with annihilation operators satisfying
the canonical anti-commutation relations. -/
class CARAlgebra (A : Type*) [Ring A] [Algebra ℂ A] [StarRing A] where
  /-- The annihilation operator a(f) for each f ∈ H. -/
  a : H → A
  /-- a is complex-linear: a(αf + βg) = αa(f) + βa(g). -/
  a_linear : ∀ (α β : ℂ) (f g : H), a (α • f + β • g) = α • a f + β • a g
  /-- CAR relation: {a(f), a*(g)} = ⟨f,g⟩ · 1. -/
  car_relation : ∀ f g, a f * star (a g) + star (a g) * a f = @inner ℂ H _ f g • (1 : A)
  /-- CAR relation: {a(f), a(g)} = 0. -/
  car_zero : ∀ f g, a f * a g + a g * a f = 0

namespace CARAlgebra

variable {H} {A : Type*} [Ring A] [Algebra ℂ A] [StarRing A] [CARAlgebra H A]

/-- a(f)² = 0 (Pauli exclusion principle).
Proof: specialize car_zero at f = g, giving a·a + a·a = 0. -/
theorem a_sq_zero (f : H) : a (A := A) f * a f = 0 := by
  have hsum : a (A := A) f * a f + a f * a f = 0 :=
    CARAlgebra.car_zero (H := H) (A := A) f f
  have hsmul : (2 : ℂ) • (a (A := A) f * a f) = 0 := by
    simpa [two_smul, two_mul] using hsum
  have h2 : (2 : ℂ) ≠ 0 := by norm_num
  exact (smul_eq_zero.mp hsmul).resolve_left h2

/-- The anti-commutator {a(f), a*(f)} = ⟨f,f⟩ · 1 implies that
a(f)a*(f) = ⟨f,f⟩ · 1 - a*(f)a(f). -/
theorem a_astar_decomp (f : H) :
    a (A := A) f * star (a f) = @inner ℂ H _ f f • (1 : A) - star (a f) * a f := by
  apply (eq_sub_iff_add_eq).2
  simpa [add_assoc, add_comm, add_left_comm] using
    (CARAlgebra.car_relation (H := H) (A := A) f f)

/-- The number operator for mode f: N_f = a*(f)a(f). -/
def numberOp (f : H) : A := star (a f) * a f

/-- N_f² = N_f (the number operator is a projection for normalized modes).
Uses a² = 0 and {a, a*} = ⟨f,f⟩ · 1. -/
theorem numberOp_idempotent (f : H) (hf : @inner ℂ H _ f f = 1) :
    numberOp (A := A) f * numberOp f = numberOp f := by
  unfold numberOp
  have hsq : a (A := A) f * a f = 0 := a_sq_zero (H := H) (A := A) f
  have hdecomp : a (A := A) f * star (a f) = @inner ℂ H _ f f • (1 : A) - star (a f) * a f :=
    a_astar_decomp (H := H) (A := A) f
  calc
    (star (a f) * a f) * (star (a f) * a f)
        = star (a f) * (a f * star (a f)) * a f := by simp [mul_assoc]
    _ = star (a f) * ((@inner ℂ H _ f f • (1 : A)) - star (a f) * a f) * a f := by rw [hdecomp]
    _ = star (a f) * (@inner ℂ H _ f f • (1 : A)) * a f - star (a f) * (star (a f) * a f) * a f := by
      simp [mul_assoc, mul_sub, sub_mul]
    _ = @inner ℂ H _ f f • (star (a f) * a f) - star (a f) * (star (a f) * (a f * a f)) := by
      simp [mul_assoc]
    _ = @inner ℂ H _ f f • (star (a f) * a f) := by simp [hsq]
    _ = star (a f) * a f := by simpa [hf]

end CARAlgebra

end Quantum
